# Generated by Django 2.0.1 on 2018-10-23 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Cursos',
                'verbose_name': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('multiple_times', models.BooleanField(default=False, verbose_name='Refazível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Experimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('quesion_type', models.CharField(choices=[('FECHADA', 'Múltipla Escolha'), ('ABERTA', 'Resposta aberta')], default='FECHADA', max_length=9, verbose_name='Tipo')),
                ('student_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada do aluno')),
                ('answer_a', models.CharField(blank=True, max_length=2048, null=True, verbose_name='a)')),
                ('answer_b', models.CharField(blank=True, max_length=2048, null=True, verbose_name='b)')),
                ('answer_c', models.CharField(blank=True, max_length=2048, null=True, verbose_name='c)')),
                ('answer_d', models.CharField(blank=True, max_length=2048, null=True, verbose_name='d)')),
                ('correct_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada correta')),
                ('student_text', models.TextField(blank=True, null=True, verbose_name='Resposta aberta do aluno')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=9, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('gender', models.CharField(choices=[('MASCULINO', 'M'), ('FEMININO', 'F')], default='MASCULINO', max_length=9, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)], verbose_name='Série')),
                ('email', models.EmailField(blank=True, max_length=256, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=9, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='aluno_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario'),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='aluno_exercicio',
            name='aluno_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario'),
        ),
        migrations.AddField(
            model_name='aluno_exercicio',
            name='exercicio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Exercicio'),
        ),
    ]
