# Generated by Django 2.0.1 on 2018-10-24 03:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma')),
            ],
        ),
        migrations.RemoveField(
            model_name='aula',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='turma_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='tema_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
            preserve_default=False,
        ),
    ]
