# Generated by Django 2.0.1 on 2018-10-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181024_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='name',
            field=models.CharField(default='Aula', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='name',
            field=models.CharField(default='Exercicio', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='name',
            field=models.CharField(default='Experimentacao', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Tema'),
        ),
    ]
