# Generated by Django 2.0.1 on 2018-10-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181024_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='tema_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='topic',
            field=models.CharField(default='topic', max_length=100, verbose_name='Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='topic',
            field=models.CharField(default='topic', max_length=100, verbose_name='Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='topic',
            field=models.CharField(default='topic', max_length=100, verbose_name='Tema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
