# Generated by Django 2.0.1 on 2018-10-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181004_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('multiple_times', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('quesion_type', models.CharField(choices=[('FECHADA', 'Múltipla Escolha'), ('ABERTA', 'Resposta aberta')], default='FECHADA', max_length=9, verbose_name='Tipo')),
                ('student_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada do aluno')),
                ('correct_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada correta')),
                ('student_text', models.TextField(blank=True, null=True, verbose_name='Resposta aberta do aluno')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('PÚBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICO', max_length=9, verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=9, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario'),
        ),
    ]
