# Generated by Django 2.0.1 on 2018-10-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181024_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_exercicio',
            name='aluno_id',
        ),
        migrations.RemoveField(
            model_name='aluno_exercicio',
            name='exercicio_id',
        ),
        migrations.RemoveField(
            model_name='aluno_turma',
            name='aluno_id',
        ),
        migrations.RemoveField(
            model_name='aluno_turma',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Aluno_Exercicio',
        ),
        migrations.DeleteModel(
            name='Aluno_Turma',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Exercicio',
        ),
        migrations.DeleteModel(
            name='Experimentacao',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
