# Generated by Django 2.0.1 on 2018-10-07 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181007_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
    ]
