# Generated by Django 2.0.1 on 2018-10-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181007_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario')),
                ('exercicio_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Usuario')),
                ('turma_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Turma')),
            ],
        ),
    ]
