# Generated by Django 2.0.1 on 2018-10-11 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_aluno_exercicio_aluno_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='turma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Turma'),
        ),
    ]
