# Generated by Django 2.0.1 on 2018-10-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20181011_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'M'), ('FEMININO', 'F')], default='MASCULINO', max_length=9, verbose_name='Sexo'),
        ),
    ]
