# Generated by Django 2.0.1 on 2018-10-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_usuario_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='course_type',
            field=models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=9, verbose_name='Tipo'),
        ),
    ]
