# Generated by Django 2.0.1 on 2018-10-24 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aula', max_length=100, verbose_name='Nome')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Exercicio', max_length=100, verbose_name='Nome')),
                ('multiple_times', models.BooleanField(default=False, verbose_name='Refazível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Experimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Experimentacao', max_length=100, verbose_name='Nome')),
                ('text_content', models.TextField(verbose_name='Conteúdo textual')),
                ('visual_content', models.CharField(max_length=2048, verbose_name='Conteúdo visual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('quesion_type', models.CharField(choices=[('FECHADA', 'Múltipla Escolha'), ('ABERTA', 'Resposta aberta')], default='FECHADA', max_length=9, verbose_name='Tipo')),
                ('student_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada do aluno')),
                ('answer_a', models.CharField(blank=True, max_length=2048, null=True, verbose_name='a)')),
                ('answer_b', models.CharField(blank=True, max_length=2048, null=True, verbose_name='b)')),
                ('answer_c', models.CharField(blank=True, max_length=2048, null=True, verbose_name='c)')),
                ('answer_d', models.CharField(blank=True, max_length=2048, null=True, verbose_name='d)')),
                ('correct_answer', models.CharField(blank=True, max_length=1, null=True, verbose_name='Resposta fechada correta')),
                ('student_text', models.TextField(blank=True, null=True, verbose_name='Resposta aberta do aluno')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=9, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
        migrations.AddField(
            model_name='aluno_turma',
            name='turma_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='aluno_exercicio',
            name='exercicio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio'),
        ),
    ]
