# Generated by Django 2.0.1 on 2018-10-25 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181024_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno_turma',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterField(
            model_name='aluno_turma',
            name='aluno_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='aluno_turma',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='aluno_turma',
            unique_together={('aluno_id', 'turma_id')},
        ),
    ]
