# Generated by Django 2.0.1 on 2018-10-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181024_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/materials')),
                ('turma_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Turma')),
            ],
        ),
        migrations.AlterField(
            model_name='aula',
            name='name',
            field=models.CharField(default='Aula X', max_length=100, verbose_name='Nome'),
        ),
    ]
