# Generated by Django 2.0.1 on 2018-10-31 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181030_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='turma_id',
        ),
        migrations.AddField(
            model_name='material',
            name='aula_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Aula'),
        ),
    ]
