# Generated by Django 2.0.1 on 2018-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181030_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentacao',
            name='name',
            field=models.CharField(default='Experimentacao', max_length=100, verbose_name='Título'),
        ),
    ]
