# Generated by Django 2.0.1 on 2018-11-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181101_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentacao',
            name='source',
            field=models.CharField(default='http://', max_length=2048, verbose_name='Fonte'),
        ),
    ]
