# Generated by Django 2.0.1 on 2018-11-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_experimentacao_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentacao',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo textual'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='visual_content',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Conteúdo visual'),
        ),
    ]
