# Generated by Django 2.0.1 on 2018-11-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181101_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='multiple_times',
            field=models.BooleanField(default=False, verbose_name='Pode ser feito mais de uma vez'),
        ),
    ]
