# Generated by Django 2.0.1 on 2018-11-06 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181102_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(default='A', max_length=1, verbose_name='Resposta')),
                ('student_text', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('aluno_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.Pergunta', verbose_name='Pergunta')),
            ],
        ),
    ]
