# Generated by Django 2.0.1 on 2018-11-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='student_answer',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='student_text',
        ),
    ]
