# Generated by Django 2.0.1 on 2018-11-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pergunta_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='numero',
            new_name='number',
        ),
    ]
