# Generated by Django 2.0.1 on 2018-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_usuario_pergunta_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_pergunta',
            name='correction',
            field=models.CharField(choices=[('C', 'Certo'), ('E', 'Errado'), ('N', 'Não corrigido')], default='N', max_length=9, verbose_name='Correção'),
        ),
        migrations.AlterField(
            model_name='usuario_pergunta',
            name='student_answer',
            field=models.CharField(default='a', max_length=1, verbose_name='Resposta'),
        ),
    ]
