# Generated by Django 2.0.1 on 2018-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181107_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_exercicio',
            name='corrects',
            field=models.IntegerField(default=0, verbose_name='Certos'),
        ),
        migrations.AddField(
            model_name='aluno_exercicio',
            name='wrongs',
            field=models.IntegerField(default=0, verbose_name='Errados'),
        ),
    ]
