# Generated by Django 2.0.1 on 2018-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_forum_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
