# Generated by Django 2.0.1 on 2018-11-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_resposta_forum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula'),
        ),
        migrations.AddField(
            model_name='forum',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio'),
        ),
        migrations.AddField(
            model_name='forum',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='answers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Respostas'),
        ),
    ]
