# Generated by Django 2.0.1 on 2018-11-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181111_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='visual_content',
        ),
    ]
