# Generated by Django 2.0.1 on 2018-11-15 02:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20181114_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='text_content',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo textual'),
        ),
    ]
