# Generated by Django 2.0.1 on 2018-11-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_aula_visual_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentacao',
            name='visual_content',
        ),
    ]
