# Generated by Django 2.0.1 on 2018-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181117_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='text_content',
            field=models.TextField(verbose_name='Conteúdo textual'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='multiple_times',
            field=models.CharField(choices=[(False, 'Não'), (True, 'Sim')], default=False, max_length=9, verbose_name='Pode ser feito mais de uma vez'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo textual'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='body',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='text',
            field=models.TextField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='reply',
            field=models.TextField(verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='usuario_pergunta',
            name='student_text',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta'),
        ),
    ]
