# Generated by Django 2.0.1 on 2018-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20181120_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='multiple_times',
            field=models.BooleanField(default=False, verbose_name='Pode ser feito mais de uma vez'),
        ),
    ]
