# Generated by Django 2.0.1 on 2018-11-23 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20181121_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aula_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Aula')),
            ],
        ),
    ]
