# Generated by Django 2.0.1 on 2018-11-23 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_aluno_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_pergunta',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Nota'),
        ),
    ]
