# Generated by Django 2.0.1 on 2018-11-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_usuario_pergunta_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_pergunta',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
