# Generated by Django 2.0.1 on 2018-11-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_usuario_pergunta_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio'),
        ),
        migrations.AddField(
            model_name='aula',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio'),
        ),
    ]
