# Generated by Django 2.0.1 on 2018-11-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20181124_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_aula',
            name='aula_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='aluno_exercicio',
            name='exercicio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio', verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio', verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao', verbose_name='Experimentacao'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao', verbose_name='Experimentacao'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio', verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio', verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='experimentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao', verbose_name='Experimentacao'),
        ),
        migrations.AlterField(
            model_name='material',
            name='aula_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Exercicio', verbose_name='Exercício'),
        ),
    ]
