# Generated by Django 2.0.1 on 2018-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20181129_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_exercicio',
            name='corrected',
        ),
        migrations.AddField(
            model_name='aluno_exercicio',
            name='score_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota da prática'),
        ),
    ]
