# Generated by Django 2.0.1 on 2018-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20181129_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='A', max_length=1, verbose_name='Resposta correta'),
        ),
    ]
