# Generated by Django 2.0.1 on 2018-12-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20181230_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='responsible',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
