# Generated by Django 2.0.1 on 2019-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190113_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='summary',
            field=models.TextField(default='Resumo default', verbose_name='Resumo'),
        ),
    ]
