# Generated by Django 2.0.1 on 2019-03-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_aula_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='class_id',
        ),
        migrations.AddField(
            model_name='forum',
            name='tema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tema', verbose_name='Tema'),
        ),
    ]
