# Generated by Django 2.0.1 on 2019-03-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190309_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/images', verbose_name='Imagem'),
        ),
    ]
