# Generated by Django 2.0.1 on 2019-03-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_aluno_experimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='turma_id',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
    ]
