# Generated by Django 2.0.1 on 2019-03-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190310_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema_Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tema')),
                ('turma_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Turma', verbose_name='Turma')),
            ],
        ),
    ]
