# Generated by Django 2.0.1 on 2019-03-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20190314_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
