# Generated by Django 2.0.1 on 2019-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190314_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
    ]
