# Generated by Django 2.0.1 on 2019-03-15 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_aula_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='aula_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
    ]
