# Generated by Django 2.0.1 on 2019-04-21 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190314_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='tema_turma',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='tema_turma',
            name='turma_id',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='experimentacao',
            name='tema_id',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='tema_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='turma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='experimentacao',
            name='turma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='forum',
            name='turma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='summary',
            field=models.TextField(default='', verbose_name='Resumo'),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.DeleteModel(
            name='Tema_Turma',
        ),
    ]
