# Generated by Django 2.0.1 on 2019-06-06 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20190424_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_aula',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluno_aula',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='aluno_exercicio',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluno_experimentacao',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='summary',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='multiple_times',
            field=models.BooleanField(default=False, verbose_name='Pode ser realizada mais de uma vez'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='exp_type',
            field=models.CharField(choices=[('CIÊNCIA', 'Ciência'), ('JOGO', 'Jogo'), ('NOTICIA', 'Notícia'), ('MÚSICA', 'Música'), ('VÍDEO', 'Vídeo')], max_length=9, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='experimentacao',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='material',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], max_length=1, verbose_name='Resposta correta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='quesion_type',
            field=models.CharField(choices=[('FECHADA', 'Múltipla Escolha'), ('ABERTA', 'Resposta aberta')], max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'M'), ('FEMININO', 'F')], max_length=9, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], max_length=9, verbose_name='Tipo'),
        ),
    ]
