# Generated by Django 2.0.1 on 2019-06-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20190606_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='experimentacao_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Experimentacao', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='material',
            name='aula_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.Aula', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], default='a', max_length=1, verbose_name='Resposta correta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='quesion_type',
            field=models.CharField(choices=[('FECHADA', 'Múltipla Escolha'), ('ABERTA', 'Resposta aberta')], default='FECHADA', max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'M'), ('FEMININO', 'F')], default='MASCULINO', max_length=9, verbose_name='Sexo'),
        ),
    ]
