# Generated by Django 2.0.1 on 2019-06-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190606_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='experimentacao_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Experimentacao', verbose_name='Experimentacao'),
        ),
        migrations.AlterField(
            model_name='document',
            name='aula_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aula', verbose_name='Aula'),
        ),
    ]
