# Generated by Django 2.0.1 on 2019-06-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20190606_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentacao',
            name='exp_type',
            field=models.CharField(choices=[('CIENCIA', 'Ciência'), ('JOGO', 'Jogo'), ('NOTICIA', 'Notícia'), ('MÚSICA', 'Música'), ('VÍDEO', 'Vídeo')], default='CIENCIA', max_length=9, verbose_name='Categoria'),
        ),
    ]
